version: '3.9'

services:
  # Service for the Ollama backend (using a custom image)
  ollama:
    build:
      context: ./ollama # Build from the Dockerfile in the ./ollama directory
    volumes:
      - ollama_data:/root/.ollama # Mount a volume to persist models
    ports:
      - "11434:11434" # Map Ollama's default port
    # Configure for NVIDIA GPU acceleration
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # No command needed here, the entrypoint script handles everything

  # Service for your custom frontend
  frontend:
    build: . # Build the image using the Dockerfile in the current directory (your frontend Dockerfile)
    ports:
      - "80:80" # Map the Nginx port to port 80 on the host
    depends_on:
      - ollama # Ensure Ollama starts before the frontend (optional but good practice)
    # Your frontend should access Ollama via http://ollama:11434/...

# Define volumes for data persistence
volumes:
  ollama_data: # This creates a named volume for Ollama data